name: solveconomy_simple
description: "경제 관련 퀴즈 모바일 애플리케이션"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.0
  gap: ^3.0.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600

    - family: GamjaFlower
      fonts:
        - asset: assets/fonts/gamja_flower/GamjaFlower-Regular.ttf
          weight: 400

